baseurl = "https://dominik1799.github.io/personal-page/"
title = "Dominik Horváth"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "dominik"

[markup.highlight]
style = "github-dark"

[params]
  author = "Dominik Horváth"
  info = "Full Stack Developer"
  description = "Personal website of Dominik Horváth"
  # keywords = "blog,developer,personal"
  avatarurl = "images/profile_pic.jpeg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Dominik1799"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/dominik-horv%C3%A1th-05aa61213/"
[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope-o fa-2x"
  weight = 3
  url = "mailto:dominik.horvath@gmail.com"

# Menu links
[[menu.main]]
  name = "CV"
  weight = 1
  url = "cv/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "blog/"