baseURL = "https://dominik1799.github.io/personal-page/"
title = "Dominik Horváth"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true

[markup.highlight]
noClasses = false

[params]
author = "Dominik Horváth"
info = "Full Stack software engineer"
avatarURL = "images/profile_pic.jpeg"
dateFormat = "January 2, 2006"
description = "Dominik Horváth's personal website"
since = 2023
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

customCSS = []
customSCSS = []
customJS = []
customRemoteJS = []


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/Dominik1799"

[[params.social]]
name = "Mail"
icon = "fa fa-2x fa-envelope-o"
weight = 2
url = "mailto:dominik.horvath@gmail.com"

[[params.social]]
name = "Linkedin"
icon = "fa fa-2x fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/dominik-horv%C3%A1th-05aa61213/"



[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "CV"
weight = 1
url = "cv/"

