apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-page-ingress
  namespace: personal-page
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - hosts:
        - dominikh.eu
        - www.dominikh.eu
      secretName: personal-page-certificate
  rules:
    - host: dominikh.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-page-service
                port:
                  number: 80
    - host: www.dominikh.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-page-service
                port:
                  number: 80
